name: main
on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: '.'

    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@main
        
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.TOKEN }}
        
      # - name: Build and push
      #   uses: docker/build-push-action@v5
      #   with:
      #     push: true
      #     tags: nestejs:latest
      
      - name: 'Build Inventory Image'
        run: |
              docker build . --tag ghcr.io/bgermano1/nestjs:latest
              docker push ghcr.io/bgermano1/nestjs:latest
          

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'ghcr.io/bgermano1/nestjs:latest'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'HIGH, CRITICAL'
        continue-on-error: true

      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
            docker pull ghcr.io/bgermano1/nestjs:latest
            docker run -d -p 3000:3000 ghcr.io/bgermano1/nestjs:latest

      - name: ZAP Scan
        uses: zaproxy/action-full-scan@v0.9.0
        with:
          token: ${{ secrets.TOKEN }}
          docker_name: 'ghcr.io/zaproxy/zaproxy:stable'
          target: 'http://20.206.251.0:3000/'
          rules_file_name: '.zap/rules.tsv'
          cmd_options: '-a'
