name: main
on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: '.'

    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@main
        
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.TOKEN }}
        
      # - name: Build and push
      #   uses: docker/build-push-action@v5
      #   with:
      #     push: true
      #     tags: nestejs:latest
      
      - name: 'Build Inventory Image'
        run: |
              docker build . --tag ghcr.io/bgermano1/nestjs:latest
              docker push ghcr.io/bgermano1/nestjs:latest
          

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'ghcr.io/bgermano1/nestjs:latest'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'HIGH, CRITICAL'
        continue-on-error: true
